spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MillCreek
    username: ${database_username}
    password: ${database_password}
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        ddl-auto: update
        jdbc:
          time_zone: UTC
server:
  port: 9651
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: keystore/keystore.p12
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: tomcat
